import { Chain, SchemaDefinition } from './types';

export const CHAINS: Chain[] = [
  // --- Ethereum L1 ---
  { 
    id: 1, 
    name: 'Ethereum', 
    color: 'blue-500', 
    graphqlUrl: 'https://easscan.org/graphql',
    vmType: 'EVM',
    group: 'Ethereum L1'
  },
  
  // --- Optimistic Rollups ---
  { 
    id: 10, 
    name: 'Optimism', 
    color: 'red-500', 
    graphqlUrl: 'https://optimism.easscan.org/graphql',
    vmType: 'EVM',
    group: 'Optimism Rollups'
  },
  { 
    id: 8453, 
    name: 'Base', 
    color: 'blue-600', 
    graphqlUrl: 'https://base.easscan.org/graphql',
    vmType: 'EVM',
    group: 'Optimism Rollups'
  },
  { 
    id: 42161, 
    name: 'Arbitrum', 
    color: 'cyan-600', 
    graphqlUrl: 'https://arbitrum.easscan.org/graphql',
    vmType: 'EVM',
    group: 'Optimism Rollups'
  },
  { 
    id: 1946, 
    name: 'Soneium', 
    color: 'slate-400', 
    // graphqlUrl: Pending
    vmType: 'EVM',
    group: 'Optimism Rollups'
  },
  { 
    id: 763373, 
    name: 'Ink', 
    color: 'purple-600', 
    // graphqlUrl: Pending
    vmType: 'EVM',
    group: 'Optimism Rollups'
  },
  { 
    id: 'tempo-testnet', 
    name: 'Tempo', 
    color: 'orange-400', 
    // graphqlUrl: Pending
    vmType: 'EVM',
    group: 'Optimism Rollups'
  },
  { 
    id: 'arc-testnet', 
    name: 'Arc', 
    color: 'indigo-400', 
    // graphqlUrl: Pending
    vmType: 'EVM',
    group: 'Optimism Rollups'
  },

  // --- ZK Rollups ---
  { 
    id: 59144, 
    name: 'Linea', 
    color: 'slate-200', 
    graphqlUrl: 'https://linea.easscan.org/graphql',
    vmType: 'EVM',
    group: 'ZK Rollups'
  },
  { 
    id: 534352, 
    name: 'Scroll', 
    color: 'amber-200', 
    graphqlUrl: 'https://scroll.easscan.org/graphql',
    vmType: 'EVM',
    group: 'ZK Rollups'
  },

  // --- Sidechains / Validium / L1s ---
  { 
    id: 137, 
    name: 'Polygon', 
    color: 'purple-500', 
    graphqlUrl: 'https://polygon.easscan.org/graphql',
    vmType: 'EVM',
    group: 'Sidechains / Validium'
  },
  { 
    id: 42220, 
    name: 'Celo', 
    color: 'green-400', 
    graphqlUrl: 'https://celo.easscan.org/graphql',
    vmType: 'EVM',
    group: 'Sidechains / Validium'
  },
  
  // --- SVM ---
  {
    id: 'solana',
    name: 'Solana',
    color: 'purple-400',
    vmType: 'SVM',
    group: 'SVM'
  },

  // --- MoveVM ---
  {
    id: 'aptos',
    name: 'Aptos',
    color: 'slate-200',
    vmType: 'MoveVM',
    group: 'MoveVM'
  },
  {
    id: 'sui',
    name: 'Sui',
    color: 'blue-300',
    vmType: 'MoveVM',
    group: 'MoveVM'
  }
];

// REAL WORLD POPULAR SCHEMAS (Based on Base, Optimism, and Eth Mainnet usage)
export const POPULAR_SCHEMAS: SchemaDefinition[] = [
  {
    uid: '0xf8b05c79f090979bf4a80270aba232dff11a10d9ca55c4f88de95317970f0de9',
    name: 'Coinbase Verified Account',
    description: 'The official verification schema from Coinbase. Confirms the wallet owner has completed KYC on Coinbase exchange.',
    provider: 'Coinbase',
    category: 'Identity',
    tags: ['KYC', 'CEX', 'Base'],
  },
  {
    uid: '0x6ab5d34260fca0cfcfbc73046ce61b3977cc41629f8d4651845e9b7f11bab1d7',
    name: 'Gitcoin Passport Score',
    description: 'Contains the Sybil resistance score generated by Gitcoin Passport. Essential for donation matching and governance.',
    provider: 'Gitcoin',
    category: 'Identity',
    tags: ['Sybil Resistance', 'Aggregator', 'Score'],
  },
  {
    uid: '0x32b5753e506972049e2187b5a5e3077751c3132e0e025816913169046777063d',
    name: 'Farcaster ID (Verifications)',
    description: 'Links an Ethereum address to a Farcaster ID (FID), proving social identity on the decentralized protocol.',
    provider: 'Farcaster',
    category: 'Social',
    tags: ['Social Graph', 'Lens', 'Base/Optimism'],
  },
  {
    uid: '0x431102227d89481977799d5257e87508098c4d32049e358b53293e50e5027582',
    name: 'World ID User',
    description: 'Verifies that the address belongs to a unique human who has verified via the Worldcoin Orb or Device.',
    provider: 'Worldcoin',
    category: 'Biometric',
    tags: ['ZK-Proof', 'PoP', 'Humanity'],
  },
  {
    uid: '0xdc5e2a2221b660c1d683664d4715502c3328ce7858c219665f80219602071850',
    name: 'Blackbird Membership',
    description: 'Restaurant loyalty and membership attestations used by the Blackbird platform on Base.',
    provider: 'Blackbird',
    category: 'Social',
    tags: ['Loyalty', 'Consumer', 'Base'],
  },
  {
    uid: '0xe88a101f80164893706037324888899889600988890989908989809809809809', // Symbolic UID for tutorial purposes
    name: 'Buildathon Participant',
    description: 'Awarded to developers who participate in Onchain Summer or Base Buildathons.',
    provider: 'Base',
    category: 'Social',
    tags: ['Developer', 'Hackathon', 'Base'],
  },
  {
    uid: '0x68df5679f090979bf4a80270aba232dff11a10d9ca55c4f88de95317970f0123',
    name: 'Guild.xyz Pin',
    description: 'Role verification from Guild.xyz, linking Discord/Telegram roles to on-chain status.',
    provider: 'Guild',
    category: 'Social',
    tags: ['Community', 'Discord', 'Roles'],
  },
  {
    uid: '0xCLIQUETEE79f090979bf4a80270aba232dff11a10d9ca55c4f88de95317970f0',
    name: 'Clique TEE Reputation',
    description: 'Privacy-preserving reputation analysis computed inside Trusted Execution Environments.',
    provider: 'Clique',
    category: 'DeFi',
    tags: ['TEE', 'Privacy', 'Compute'],
  },
  {
    uid: '0xMETADATA79f090979bf4a80270aba232dff11a10d9ca55c4f88de95317970f0',
    name: 'EAS Metadata',
    description: 'Standard metadata attestation used to attach names or descriptions to other schemas or UIDs.',
    provider: 'EAS',
    category: 'Governance',
    tags: ['Utility', 'System'],
  }
];